networks: {}
services:
  openldap:
    image: bitnami/openldap:2
    ports: []
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks: []
    volumes: []
  nextcloud:
    image: 'nextcloud'
    networks: []
    ports: []
volumes:
  openldap_data:
    driver: local
